### ISSUE TITLE
Use SSL with customer certificate to access Kubeflow dashboard

### ISSUE THREAD

**Issue by davecore82** [juju-solutions/bundle-cert-manager#1]
Feature request to enable accessing the Kubeflow dashboard via HTTPS/SSL with a certificate signed by someone's own Certificate Authority. Something like the TLS/HTTPS section of the Keystone charm (https://jaas.ai/keystone).

The goal would be to put those 3 files (SSL CA, SSL certificate and SSL key) somewhere in Kubernetes or Kubeflow or cert-manager and then forget about it. The certificate could be a wildcard certificate or unique certificates for each hostname.

Possibly using the CA configuration from https://cert-manager.io/docs/configuration/ (although maybe the external option would be a better fit?)

**Comment by knkski** [comment]
@davecore82: The cert-manager bundle has been split off into it's own repository. Can you try the instructions shown in README.md for configuring a CA Issuer, which seems like it should accomplish what you're looking for here?

**Comment by rui-vas** [comment]
Has this issue been tackled?

**Comment by knkski** [comment]
@davecore82 do you need anything more from this issue?

**Comment by davecore82** [comment]
@knkski Hi, sorry I've been out of the kubeflow ecosystem for a while. Were you referring to https://github.com/canonical/bundle-cert-manager ?

**Comment by davecore82** [comment]
@knkski So you're saying users should use `juju config cert-manager-controller ca-issuers='foo: ca: secretName: foo-secret' `? 

Can you explain how Charmed cert-manager, Charmed Kubeflow and Charmed Kubernetes all come together to allow Kubeflow to use a custom SSL cert? Maybe we need documentation with examples on how to use different SSL cert configurations?

**Comment by knkski** [comment]
@davecore82: I think we'll need more details about the requirements here. Offhand, it seems like Kubeflow and other services shouldn't be involved in this directly, and you'd have a relation between cert-manager and your ingress provider (such as Istio) that configures your ingress to support HTTPS.

**Comment by davecore82** [comment]
@knkski Originally, the request was to be able to use a customer provided SSL CA certificate to access Kubeflow.  The use case is that a customer has a CA and wants their users to access Kubeflow from their workstations that already trusts that CA.

I understand that cert-manager should be able to use an external CA and sign SSL certs on behalf of that external CA.  Then the ingress/istio in Kubernetes can get a cert from cert-manager and apply it to the Kubeflow dashboard, so that the users can trust it.

I don't doubt that it works, but it would be good to test and document to make sure.
