### ISSUE TITLE
Feature request - add support for podSecurityPolicy

### ISSUE THREAD

**Issue by xavpaice** [juju-solutions/bundle-cert-manager#4]
When deploying this application using helm, we can set the following options:

podSecurityPolicy: enabled: true useAppArmor: true

Our use case requires these options for the charmed deployment.

See https://pastebin.ubuntu.com/p/4F6gXfBQYY/ for an example of what adding this change in helm does to modify the yaml definitions (includes another change to prometheus as well).

**Comment by knkski** [comment]
This seems more like a feature that Juju should have, see the bug I filed here: https://bugs.launchpad.net/juju/+bug/1907709

That being said, manually handling this config could probably happen in the meantime
