### ISSUE TITLE
Issue with README documentation

### ISSUE THREAD

**Issue by jeff-hillman** [juju-solutions/bundle-cert-manager#8]
In the README.md it mentions a security role that needs to be patched for cert-manager-webhook.  There is an errant COMMA ',' on line 18 after [list]" that causes a problem.

People following these instruction verbatim will have a failure at this point.

**Comment by josephillips85** [comment]
Also the configuration of resources is wrong
is secrets (with s) no secret

 ],
      "resources": [
        "pods",
        "secret"
      ],
